# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('body', models.TextField(blank=True, help_text='The body of the Post')),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-update_date'],
            },
        ),
    ]
