# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160113_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_left',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_right',
        ),
        migrations.AddField(
            model_name='post',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='blog.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='blog.Post'),
        ),
    ]
